import { Inter } from "next/font/google";
import "./globals.css";
import ContexProvider from "@/contex/ContexProvider";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "ModernMart – Next-Gen Shopping Experience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-slate-100 min-h-screen text-slate-900 flex flex-col`}>
        <ContexProvider>
          <Navbar/>
          <main className="flex-1">
            {children}
          </main>
          <Footer/>
        </ContexProvider>
        <ToastContainer
        theme="dark"
        />
      </body>
    </html>
  );
}
